# Generated by Django 5.0.6 on 2024-05-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_reminder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
