# Generated by Django 5.0.6 on 2024-05-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_reminder_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='amenities/icons/')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='beds',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='amenities',
            field=models.ManyToManyField(to='service.amenity'),
        ),
    ]
