# Generated by Django 5.0.6 on 2024-05-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_amenity_room_beds_roomtype_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default=None, upload_to='room_images/'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(default=None, upload_to='roomtype_images/'),
        ),
    ]
